### ISSUE TITLE
Is the prompt construction tool provided?

### ISSUE THREAD

**Issue by LiuWenJia-ops** [yafuly/PromptNMT#1]
Hi, I read about the paper. It's a very good job!
But I didn't find the prompt construction tool mentioned in the 4.3 part; maybe it's a script I missed?
Thx for your reply!

**Comment by yafuly** [comment]
> construction

Hi Wenjia,

Thanks for your interest. Do you mean `Prompt Construction Pool'? 

The prompts are constructed automatically based on phrase alignments (induced by fast-align or giza++). Given monolingual phrases or aligned bilingual phrase pairs, we construct three types of prompts in the way illustrated in Section 4.3. 

Contact me if you have further questions (my wechat: dirl11).

Best,

Yafu

**Comment by yafuly** [comment]
Hi Wenjia,

Thanks for your interest. Do you mean `Prompt Construction Pool'?

The prompts are constructed automatically based on phrase alignments (induced by fast-align or giza++). Given monolingual phrases or aligned bilingual phrase pairs, we construct three types of prompts in the way illustrated in Section 4.3.

Contact me if you have further questions (my wechat: dirl11).

Best,

Yafu
