### ISSUE TITLE
Prompt construction tool

### ISSUE THREAD

**Issue by YHwzt** [yafuly/PromptNMT#2]
I think this is a very meaningful job and I would like to try to reproduce it.But I'm having some problems reproducing the transformer with prompt

I saw your conversation with Wenjia. I also encountered the same problem.  could you please share the prompt construction tool with me?
If possible, please allow me to add your WeChat

Looking forward to your reply.

**Comment by yafuly** [comment]
Hi,

Sure. You can add my wechat for further communication.
