### ISSUE TITLE
Prompt Construction

### ISSUE THREAD

**Issue by Ariel19977** [yafuly/PromptNMT#3]
Hi, It's a great job!  I am trying to reproduce the experiment in this paper.  But it did not achieve the same excellent results as in the paper. I think there should be a difference in the prompt construction method. And I tried to contact you via WeChat ID（dirl11） but failed to find the number. 😭 
Can you share this construction tool to me and guide me on some of the difficulties I'm having?
If it is convenient, please allow me to contact you.
Looking forward to your reply！

**Comment by yafuly** [comment]
Hi,

Maybe you can leave your email and I can send you the prompt construction code.

**Comment by Ariel19977** [comment]
> Hi,
> 
> Maybe you can leave your email and I can send you the prompt construction code.


Thank you very much for your reply and help， my emai is "xulinru9797@163.com" !
